# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'l']
quit = ['q', 'ctrl+c']
cd_quit = ['Q', '']

# movement
list_up = ['up', 'k']
list_down = ['down', 'j']
page_up = ['pgup','']
page_down = ['pgdown','']
# file panel control
create_new_file_panel = ['n', '']
close_file_panel = ['w', '']
next_file_panel = ['tab', 'L']
previous_file_panel = ['shift+left', 'H']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']
# change focus
focus_on_process_bar = ['P', '']
focus_on_sidebar = ['s', '']
focus_on_metadata = ['m', '']
# create file/directory and rename
file_panel_item_create = ['a', '']
file_panel_item_rename = ['r', '']
# file operations
copy_items = ['y', '']
cut_items = ['d', '']
paste_items = ['p', 'ctrl+w', '']
delete_items = ['D', 'delete', '']
permanently_delete_items = ['ctrl+d', '']
# compress and extract
extract_file = ['x', '']
compress_file = ['X', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# other
pinned_directory = ['<', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
open_spf_prompt = ['>', '']
copy_path = ['Y', '']
copy_present_working_directory = ['c', '']
toggle_footer = ['F', '']
open_zoxide = ['z', '']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', 'left', 'backspace']
search_bar = ['/', '']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['V', '']
